-- Ejecutar en el SERVIDOR (phpMyAdmin -> BD del sistema -> SQL)
-- Repara AUTO_INCREMENT perdido al importar la BD.
-- No borra datos; solo corrige la columna id.

ALTER TABLE documents MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE newpages MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE users MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE employees MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE institutions MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE categories MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE levels MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE charges MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE clases MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE salaries MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE salcats MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE drafts MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE contacts MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
